version: 2

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
       mkdir -p workspace
       git clone -b validateNightlyNew git@github.com:CDAT/cdat workspace/cdat
       # install_miniconda.py installs miniconda3 under $WORKDIR/miniconda
       python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'

  - &conda_rerender
    name: conda_rerender
    command: |
       git clone -b feedstock_recipe https://github.com/CDAT/conda-recipes.git $WORKDIR/conda-recipes 
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       BUILD_SCRIPT="$WORKDIR/conda-recipes/build_tools/conda_build.py"
       python $BUILD_SCRIPT -w $WORKDIR -l $LAST_STABLE -B 0 -p $PKG_NAME -r $REPO_NAME -b $CIRCLE_BRANCH --do_rerender

  - &conda_build
    name: conda_build
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       python --version
       conda config --add channels conda-forge --force
       conda config --add channels cdat/label/nightly --force
       conda config --set channel_priority strict
       BUILD_SCRIPT="$WORKDIR/conda-recipes/build_tools/conda_build.py"
       python $BUILD_SCRIPT -w $WORKDIR -p $PKG_NAME -r $REPO_NAME --build_version $BUILD_VARIANT_VER --do_build

  - &setup_run_tests
    name: setup_run_tests
    environment:
       PKGS: "testsrunner pytest"
       CHANNELS: "-c cdat/label/nightly -c conda-forge"
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda create -y -n test_libcf --use-local $CHANNELS "$CONDA_PY_VER" $PKG_NAME $PKGS $COVERAGE_PKGS
       conda activate test_libcf
       conda list
       conda list --verbose libcf

  - &run_tests
    name: run_tests
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate test_libcf
       python run_tests.py -H -v2 -n 1 `pwd`/tests/test_big_array.py
       mv tests/test_big_array.py $WORKDIR/
       python run_tests.py -H -v2 --subdir $COVERAGE
    no_output_timeout: 60m

  - &conda_upload
    name: conda_upload
    command: |
       if [[ $CIRCLE_BRANCH != "master" ]]; then
          exit 0
       fi
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       UPLOAD_OPTIONS="-t $CONDA_UPLOAD_TOKEN upload -u $USER -l $LABEL"
       anaconda $UPLOAD_OPTIONS linux_build/miniconda/conda-bld/linux-64/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force
       anaconda $UPLOAD_OPTIONS macos_build/miniconda/conda-bld/osx-64/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force

  - &run_coveralls
    name: run_coveralls
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate $ENV_NAME
       coveralls
       conda deactivate

jobs:
   macos_setup:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         LAST_STABLE: "1.0.3"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *conda_rerender
         - persist_to_workspace:
              root: .
              paths: 
                 - macos_build

   linux_setup:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         LAST_STABLE: "1.0.3"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *conda_rerender
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build

   #
   # nompi
   # 
   macos_libcf_nompi_py36:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.6,<3.7"
         BUILD_VARIANT_VER: "mpinompipython3.6"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/libcf*tar.bz2

   macos_libcf_nompi_py37:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "mpinompipython3.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/libcf*tar.bz2

   macos_libcf_nompi_py38:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.8,<3.9"
         BUILD_VARIANT_VER: "mpinompipython3.8"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/libcf*tar.bz2

   linux_libcf_nompi_py36:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.6,<3.7"
         BUILD_VARIANT_VER: "mpinompipython3.6"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/libcf*tar.bz2

   linux_libcf_nompi_py37:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "mpinompipython3.7"
         COVERAGE: "-c /home/circleci/project/tests/coverage.json"
         COVERAGE_PKGS: "coverage coveralls"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/libcf*tar.bz2

   linux_libcf_nompi_py38:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.8,<3.9"
         BUILD_VARIANT_VER: "mpinompipython3.8"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/libcf*tar.bz2

   #
   # openmpi
   #
   macos_libcf_openmpi_py36:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.6,<3.7"
         BUILD_VARIANT_VER: "mpiopenmpipython3.6"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/libcf*tar.bz2

   macos_libcf_openmpi_py37:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "mpiopenmpipython3.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/libcf*tar.bz2

   macos_libcf_openmpi_py38:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.8,<3.9"
         BUILD_VARIANT_VER: "mpiopenmpipython3.8"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/libcf*tar.bz2

   linux_libcf_openmpi_py36:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.6,<3.7"
         BUILD_VARIANT_VER: "mpiopenmpipython3.6"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/libcf*tar.bz2

   linux_libcf_openmpi_py37:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "mpiopenmpipython3.7"
         COVERAGE: "-c /home/circleci/project/tests/coverage.json"
         COVERAGE_PKGS: "coverage coveralls"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/libcf*tar.bz2

   linux_libcf_openmpi_py38:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.8,<3.9"
         BUILD_VARIANT_VER: "mpiopenmpipython3.8"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/libcf*tar.bz2

   #
   # mpich
   #
   macos_libcf_mpich_py36:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.6,<3.7"
         BUILD_VARIANT_VER: "mpimpichpython3.6"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/libcf*tar.bz2

   macos_libcf_mpich_py37:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "mpimpichpython3.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/libcf*tar.bz2

   macos_libcf_mpich_py38:
      macos:
         xcode: "11.1.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.8,<3.9"
         BUILD_VARIANT_VER: "mpimpichpython3.8"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/libcf*tar.bz2

   linux_libcf_mpich_py36:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.6,<3.7"
         BUILD_VARIANT_VER: "mpimpichpython3.6"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/libcf*tar.bz2

   linux_libcf_mpich_py37:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "mpimpichpython3.7"
         COVERAGE: "-c /home/circleci/project/tests/coverage.json"
         COVERAGE_PKGS: "coverage coveralls"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/libcf*tar.bz2

   linux_libcf_mpich_py38:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "libcf"
         REPO_NAME: "libcf"
         ENV_NAME: "test_libcf"
         CONDA_PY_VER: "python>=3.8,<3.9"
         BUILD_VARIANT_VER: "mpimpichpython3.8"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/libcf*tar.bz2

   upload:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "libcf"
         VERSION: "1.0.3"
         USER: "cdat"
         LABEL: "nightly"
         LABEL: "mpi_variant"
      steps:
         - attach_workspace:
              at: .
         - run: pwd
         - run: *conda_upload

workflows:
   version: 2
   libcf:
      jobs:
         - macos_setup
         - linux_setup
         - macos_libcf_nompi_py36:
              requires:
                 - macos_setup
         - macos_libcf_nompi_py37:
              requires:
                 - macos_setup
         - macos_libcf_nompi_py38:
              requires:
                 - macos_setup
         - linux_libcf_nompi_py36:
              requires:
                 - linux_setup
         - linux_libcf_nompi_py37:
              requires:
                 - linux_setup
         - linux_libcf_nompi_py38:
              requires:
                 - linux_setup

         - macos_libcf_openmpi_py36:
              requires:
                 - macos_setup
         - macos_libcf_openmpi_py37:
              requires:
                 - macos_setup
         - macos_libcf_openmpi_py38:
              requires:
                 - macos_setup
         - linux_libcf_openmpi_py36:
              requires:
                 - linux_setup
         - linux_libcf_openmpi_py37:
              requires:
                 - linux_setup
         - linux_libcf_openmpi_py38:
              requires:
                 - linux_setup

         - macos_libcf_mpich_py36:
              requires:
                 - macos_setup
         - macos_libcf_mpich_py37:
              requires:
                 - macos_setup
         - macos_libcf_mpich_py38:
              requires:
                 - macos_setup
         - linux_libcf_mpich_py36:
              requires:
                 - linux_setup
         - linux_libcf_mpich_py37:
              requires:
                 - linux_setup
         - linux_libcf_mpich_py38:
              requires:
                 - linux_setup

         - upload:
              requires:
                 - macos_libcf_nompi_py36
                 - macos_libcf_nompi_py37
                 - macos_libcf_nompi_py38
                 - linux_libcf_nompi_py36
                 - linux_libcf_nompi_py37
                 - linux_libcf_nompi_py38
                 - macos_libcf_openmpi_py36
                 - macos_libcf_openmpi_py37
                 - macos_libcf_openmpi_py38
                 - linux_libcf_openmpi_py36
                 - linux_libcf_openmpi_py37
                 - linux_libcf_openmpi_py38
                 - macos_libcf_mpich_py36
                 - macos_libcf_mpich_py37
                 - macos_libcf_mpich_py38
                 - linux_libcf_mpich_py36
                 - linux_libcf_mpich_py37
                 - linux_libcf_mpich_py38

