/* This is part of the netCDF package. Copyright 2005 University
   Corporation for Atmospheric Research/Unidata See COPYRIGHT file for
   conditions of use. See www.unidata.ucar.edu for more info.

   Test libcf file stuff.

   $Id: tst_princeton.c 828 2011-09-14 20:05:08Z pletzer $
*/

#include <cf_config.h>
#include <libcf_src.h>
#include <netcdf.h>
#include <nc_tests.h>

#define FILE_NAME "tst_princeton.nc"

int
main(int argc, char **argv)
{
   printf("\n*** Testing GRIDSPEC Princeton API.\n");
   printf("*** testing simple regular lon/lat grid creation...");
   {
#define START_LAT 0
#define DELTA_LAT .5
#define START_LON 50
#define DELTA_LON .5
#define NLON 60
#define NLAT 20
#define NXBNDS 2
#define NYBNDS 2
#define NRATIO 1
#define SIMPLE_DX ((double)0)
#define SIMPLE_DY ((double)0)
#define NTILEX 0
#define NTILEY 0
#define MAXBOUNDS 2
#define NDIMS 2
      char gridname[] = "tst_princeton_reglonlat_1";
      char center[] = "none";
      char history[] = "libcf/gridspec/libsrc/tst_princeton.c: testing simple hgrid creation for libcf library.";
      int  ndivx[] = {1};
      int  ndivy[] = {1};
      double xbnds[MAXBOUNDS] = {0, 30};
      double ybnds[MAXBOUNDS] = {50, 60};
      double lon[NLON], lat[NLAT];
      int ncid, gridid;
      int grid_dimid[NDIMS], grid_varid[NDIMS];
      int x, y;

      nccf_set_log_level(5);

      /* Initialize coordinate data. */
      for (x = 0; x < NLON; x++)
	 lon[x] = START_LON + x * DELTA_LAT;
      for (x = 0; x < NLAT; x++)
	 lon[x] = START_LAT + x * DELTA_LAT;

      /* Do everything to generate the grid generated by the following test:
	 echo "*** generating regular lon-lat grid (supergrid size 60x20)..."
	 ./make_hgrid --grid_type regular_lonlat_grid --nxbnd 2 --nybnd 2                   
	 --xbnd 0,30 --ybnd 50,60  --nlon 60 --nlat 20 */
      if (nc_create(FILE_NAME, NC_CLOBBER, &ncid)) ERR;
      if (nccf_def_latitude(ncid, NXBNDS, NC_DOUBLE, &grid_dimid[0], &grid_varid[0])) ERR;
      if (nccf_def_longitude(ncid, NYBNDS, NC_DOUBLE, &grid_dimid[1], &grid_varid[1])) ERR;
      /*if (nccf_def_grid(ncid, NDIMS, grid_dimid, &gridid)) ERR;*/
      /*if (nccf_put_grid(ncid, gridid)) ERR;*/
      if (nc_close(ncid)) ERR;
      /*if (nccf_close_grid(gridid)) ERR;*/
   }
   SUMMARIZE_ERR;
   FINAL_RESULTS;
}

